#:schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = " {{ .Folder }} :: {{if .Root}}Admin{{end}}"
version = 3
final_space = true
# terminal_background = "p:t-background"

[palette]
white-blue = "#a9b1d6"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "blue"
  template = "\u279c "

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "magenta"
  template = "<b>{{ .Path }}</b>"

    [blocks.segments.properties]
    style = "folder"
  
  [[blocks.segments]]
  type = 'git'
  style = 'plain'
  foreground = 'grey'
  background = 'transparent'
  template = """ \
    git:(<red>{{ .HEAD }}</>\
    {{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}\
    <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>)\
    """

    [blocks.segments.properties]
    fetch_status = true
    branch_icon = ""


  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "red"
  template = " \uf00d"

[[blocks]]
type = "prompt"
alignment = "right"
overflow = "hide"

  [[blocks.segments]]
  type = "node"
  style = "plain"
  foreground = "lightGreen"
  template = "\ue718 {{ .Full }} "

  [[blocks.segments]]
  type = "php"
  style = "plain"
  foreground = "blue"
  template = "\ue73d {{ .Full }} "

  [[blocks.segments]]
  type = "python"
  style = "plain"
  foreground = "yellow"
  template = "\uE235 {{ .Full }}"

  [[blocks.segments]]
  type = "julia"
  style = "plain"
  foreground = "magenta"
  template = "\uE624 {{ .Full }}"

  [[blocks.segments]]
  type = "ruby"
  style = "plain"
  foreground = "red"
  template = "\uE791 {{ .Full}}"

  [[blocks.segments]]
  type = "go"
  style = "plain"
  foreground = "lightBlue"
  template = "\uFCD1 {{ .Full}}"

  [[blocks.segments]]
  type = "command"
  style = "plain"
  foreground = "p:white-blue"

    [blocks.segments.properties]
    command = "git log --pretty=format:%cr -1 || date +%H:%M:%S"
    shell = "bash"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "lightGreen"
  template = "\u25b6"

  [secondary_prompt]
  foreground = "blue"
  template = "\u25b6 "

  [transient_prompt]
  foreground = "magenta"
  template = "\u279c "
