palette = "catppuccin_macchiato"

[character]
success_symbol = " [ ](mauve)"
error_symbol = " [ ](red)"

[aws]
symbol = "  "

[c]
symbol = " "

[directory]
truncation_length = 7

[hostname]
ssh_only = true
format = '[$hostname](bold underline green) '
trim_at = "."
disabled = false

[username]
style_user = "blue bold"
style_root = "red bold"
format = "[$user]($style) on "
disabled = false
show_always = false

[git_branch]
symbol = " "

[git_status]
ahead = "${count}"
behind = "${count} [PULL NEEDED](blink red)"
conflicted = "[=](blink red)"
diverged = "[󰯎](blink red) ${ahead_count}${behind_count}"
up_to_date = "[](green)"
untracked = "[?](dimmed text)"
stashed = "[$](green)"
modified = "[!](yellow)(yellow)"
renamed = ""
deleted =""
staged = '[++\($count\)](green)'
format='[\[](bold pink)$all_status$ahead_behind[\] ](bold pink)'

[hg_branch]
symbol = " "

[nodejs]
symbol="󰎙"
format='[\[](bold)[$symbol](bold green) [$version](bold green)[\]](bold)'

[python]
symbol = " "

[rust]
symbol = " "

# Palette colors
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
